version: "3"

services:
  bmstu_web_homework:
    container_name: bmstu_web_homework
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    networks:
      - net

  postgres:
    image: postgres:14.8-alpine
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=965MB"
      - "-c"
      - "effective_cache_size=2897MB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=241MB"
      - "-c"
      - "random_page_cost=1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=0"
      - "-c"
      - "idle_in_transaction_session_timeout=15min"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=512"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements" #pg_store_plans
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "autovacuum_analyze_scale_factor=0.01"
      - "-c"
      - "autovacuum_max_workers=8"
      - "-c"
      - "autovacuum_naptime=1s"
      - "-c"
      - "autovacuum_vacuum_cost_delay=5ms"
      - "-c"
      - "autovacuum_vacuum_scale_factor=0.01"
      - "-c"
      - "autovacuum_work_mem=-1"
      - "-c"
      - "default_toast_compression=lz4"
      - "-c"
      - "effective_cache_size=2897MB"
      - "-c"
      - "idle_in_transaction_session_timeout=15min"
      - "-c"
      - "log_autovacuum_min_duration=50ms"
      - "-c"
      - "wal_compression=on"
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
      - ./logs:/var/lib/postgresql/data/pg_log
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
    networks:
      - net

networks:
  net:
    driver: bridge
